### ISSUE TITLE
无法生成bigportraaits和images文件夹

### ISSUE THREAD

**Issue by Buzzshock** [zhnkc9/skin-generator#1]
可以正常生成anim文件夹，里面的内容也正常，但是无法生成bigportraits和images文件夹。我直接把filter.txt删了，这样过滤器就不起作用了，保险起见还是想问一下这样操作是否正确呢？

**Comment by zhnkc9** [comment]
lua代码直接hook了物品图标获取的接口,所以就不需要images和bigportraits了
其他的动画文件是首次运行自动copy到mod中
